/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.FacultyView;

import Controllers.Controller;
import Models.Course;
import Models.Course_Model;
import Models.User;
import Views.View;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Quan's PC
 */
public class FacultyRegisterWithdrawCourseView extends javax.swing.JFrame implements View{
    User faculty; 
    private List<Course> courseList;
    DefaultTableModel dtmCourseList;
    /**
     * Creates new form AdminMenuView
     */
    public FacultyRegisterWithdrawCourseView() {
        initComponents();
        setTitle("Faculty Register and Withdraw Course");
        faculty = Controller.getUser();
        registerCourseCheckBox.setSelected(true);
        renderTable(Course_Model.getCoursesByUserId(faculty.getUserId(), "faculty", ""));
    }
    
    private void readCourses(){
        int cnt = 1;
        for(Course c : courseList){
            dtmCourseList.addRow(c.toObject(cnt++));
        }
    }
    
     @Override
    public <E> void renderTable(List<E> listCourseResult){
        dtmCourseList = (DefaultTableModel) facultyCourseListTable.getModel();
        courseList = (List<Course>) listCourseResult;
        dtmCourseList.setRowCount(0);
        readCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jScrollPane1 = new javax.swing.JScrollPane();
        facultyCourseListTable = new javax.swing.JTable();
        viewCoursesTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        couseIdLabelTitle = new javax.swing.JLabel();
        courseIdFieldFind = new javax.swing.JTextField();
        registerCourseCheckBox = new javax.swing.JCheckBox();
        searchFacultyListCourseBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        CourseIdFieldRegister = new javax.swing.JTextField();
        courseIdLabelTitle = new javax.swing.JLabel();
        registerFacultyToCouresBtn = new javax.swing.JButton();
        withdrawFacultyFromCouresBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        backViewListCourseBtn = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("StudentID:");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton3.setText("Search");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(362, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1187, 580));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FACULTY REGISTER WITHDRAW COURSES");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);
        jPanel1.add(filler1, java.awt.BorderLayout.PAGE_START);

        facultyCourseListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idx", "Course_Id", "Course_name", "Course_credits", "Course_maxStudent", "Course_location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        facultyCourseListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facultyCourseListTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(facultyCourseListTable);
        if (facultyCourseListTable.getColumnModel().getColumnCount() > 0) {
            facultyCourseListTable.getColumnModel().getColumn(0).setMaxWidth(50);
            facultyCourseListTable.getColumnModel().getColumn(2).setMinWidth(200);
            facultyCourseListTable.getColumnModel().getColumn(5).setMaxWidth(70);
        }

        couseIdLabelTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        couseIdLabelTitle.setText("CourseID:");

        courseIdFieldFind.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        registerCourseCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registerCourseCheckBox.setText("Regitsered Course");

        searchFacultyListCourseBtn.setText("Search");
        searchFacultyListCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFacultyListCourseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(couseIdLabelTitle)
                        .addGap(18, 18, 18)
                        .addComponent(courseIdFieldFind, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(searchFacultyListCourseBtn)
                        .addGap(0, 237, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(registerCourseCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(couseIdLabelTitle)
                    .addComponent(courseIdFieldFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registerCourseCheckBox)
                .addGap(24, 24, 24)
                .addComponent(searchFacultyListCourseBtn)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        viewCoursesTabbedPane.addTab("View Courses", jPanel2);

        CourseIdFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        courseIdLabelTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        courseIdLabelTitle.setText("CourseID:");

        registerFacultyToCouresBtn.setText("Register");
        registerFacultyToCouresBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerFacultyToCouresBtnActionPerformed(evt);
            }
        });

        withdrawFacultyFromCouresBtn.setText("Withdraw");
        withdrawFacultyFromCouresBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawFacultyFromCouresBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(courseIdLabelTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CourseIdFieldRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(registerFacultyToCouresBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(withdrawFacultyFromCouresBtn)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CourseIdFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseIdLabelTitle))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerFacultyToCouresBtn)
                    .addComponent(withdrawFacultyFromCouresBtn))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        viewCoursesTabbedPane.addTab("Register - Withdraw Course", jPanel3);

        backViewListCourseBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backViewListCourseBtn.setText("Back");
        backViewListCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backViewListCourseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(backViewListCourseBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(backViewListCourseBtn)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewCoursesTabbedPane)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewCoursesTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backViewListCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backViewListCourseBtnActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new FacultyMenuView().setVisible(true);
    }//GEN-LAST:event_backViewListCourseBtnActionPerformed

    private void searchFacultyListCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFacultyListCourseBtnActionPerformed
        // TODO add your handling code here:
        CourseIdFieldRegister.setText("");
        String courseId = courseIdFieldFind.getText();
        boolean isReistered = registerCourseCheckBox.isSelected();        
        
        if(isReistered)
        Controller.userViewRegisterCourseController(faculty.getUserId()+"", faculty.getUserRole(), courseId,this,this);
        else
        Controller.userViewCourseByIdController(courseId, true, this);
    }//GEN-LAST:event_searchFacultyListCourseBtnActionPerformed

    private void registerFacultyToCouresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerFacultyToCouresBtnActionPerformed
        // TODO add your handling code here:
        courseIdFieldFind.setText("");
        registerCourseCheckBox.setSelected(false);
        String courseId = CourseIdFieldRegister.getText();
        Controller.userRegisterByCourseIdController(courseId, this);
        CourseIdFieldRegister.setText("");
        registerCourseCheckBox.setSelected(true);
        renderTable(Course_Model.getCoursesByUserId(Controller.getUser().getUserId(), "faculty", ""));
    }//GEN-LAST:event_registerFacultyToCouresBtnActionPerformed

    private void withdrawFacultyFromCouresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawFacultyFromCouresBtnActionPerformed
        // TODO add your handling code here:
        courseIdFieldFind.setText("");
        registerCourseCheckBox.setSelected(false);
        String courseId = CourseIdFieldRegister.getText();
        Controller.userWithdrawByCourseIdController(courseId, this);
        CourseIdFieldRegister.setText("");
        registerCourseCheckBox.setSelected(true);
        renderTable(Course_Model.getCoursesByUserId(Controller.getUser().getUserId(), "faculty", ""));
    }//GEN-LAST:event_withdrawFacultyFromCouresBtnActionPerformed

    private void facultyCourseListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultyCourseListTableMouseClicked
        // TODO add your handling code here:
        int row = facultyCourseListTable.getSelectedRow();
        CourseIdFieldRegister.setText(dtmCourseList.getValueAt(row, 1).toString());
    }//GEN-LAST:event_facultyCourseListTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyRegisterWithdrawCourseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyRegisterWithdrawCourseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyRegisterWithdrawCourseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyRegisterWithdrawCourseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyRegisterWithdrawCourseView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CourseIdFieldRegister;
    private javax.swing.JButton backViewListCourseBtn;
    private javax.swing.JTextField courseIdFieldFind;
    private javax.swing.JLabel courseIdLabelTitle;
    private javax.swing.JLabel couseIdLabelTitle;
    private javax.swing.JTable facultyCourseListTable;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JCheckBox registerCourseCheckBox;
    private javax.swing.JButton registerFacultyToCouresBtn;
    private javax.swing.JButton searchFacultyListCourseBtn;
    private javax.swing.JTabbedPane viewCoursesTabbedPane;
    private javax.swing.JButton withdrawFacultyFromCouresBtn;
    // End of variables declaration//GEN-END:variables
}
