/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.CourseView;
    
import Views.AdminView.*;
import Controllers.Controller;
import Models.Course;

/**
 *
 * @author Quan's PC
 */
public class CourseEditInformationView extends javax.swing.JFrame {
    private Course course;
    /**
     * Creates new form AdminMenuView
     */
    public CourseEditInformationView() {
        initComponents();
    }
    
    public CourseEditInformationView(Course course) {
        initComponents();
        setTitle("Course Edit Information");
        setCourse(course);
    }
    
    

    public void setCourse(Course course) {
        this.course = course;
        courseNameLabelShow.setText(this.course.getCourseName());
        courseCreditsFieldEdit.setText(this.course.getCourseCredits()+"");
        courseMaxStudentsFieldEdit.setText(this.course.getMaxStudentsRegister()+"");
        courseLocationFieldEdit.setText(this.course.getCourseLocation());
    }

    public Course getCourse() {
        return course;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel2 = new javax.swing.JPanel();
        courseNameLabelEdit = new javax.swing.JLabel();
        courseCreditsLabelEdit = new javax.swing.JLabel();
        courseMaxStudentsLabelEdit = new javax.swing.JLabel();
        courseLocationLabelEdit = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        doneEditCourseBtn = new javax.swing.JButton();
        backEditCourseBtn = new javax.swing.JButton();
        courseLocationFieldEdit = new javax.swing.JTextField();
        courseCreditsFieldEdit = new javax.swing.JTextField();
        courseMaxStudentsFieldEdit = new javax.swing.JTextField();
        courseNameLabelShow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COURSE EDIT INFORMATION");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);
        jPanel1.add(filler1, java.awt.BorderLayout.PAGE_START);

        courseNameLabelEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseNameLabelEdit.setText("Course Name:");

        courseCreditsLabelEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseCreditsLabelEdit.setText("Course Credits:");

        courseMaxStudentsLabelEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseMaxStudentsLabelEdit.setText("Course Max Students:");

        courseLocationLabelEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseLocationLabelEdit.setText("Course Location:");

        doneEditCourseBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        doneEditCourseBtn.setText("Done");
        doneEditCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneEditCourseBtnActionPerformed(evt);
            }
        });

        backEditCourseBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backEditCourseBtn.setText("Back");
        backEditCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backEditCourseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(backEditCourseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doneEditCourseBtn)
                .addGap(48, 48, 48))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneEditCourseBtn)
                    .addComponent(backEditCourseBtn)))
        );

        courseLocationFieldEdit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        courseCreditsFieldEdit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        courseMaxStudentsFieldEdit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        courseNameLabelShow.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        courseNameLabelShow.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseNameLabelEdit)
                    .addComponent(courseCreditsLabelEdit)
                    .addComponent(courseMaxStudentsLabelEdit)
                    .addComponent(courseLocationLabelEdit))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(courseMaxStudentsFieldEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                        .addComponent(courseLocationFieldEdit)
                        .addComponent(courseCreditsFieldEdit, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(courseNameLabelShow))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseNameLabelEdit)
                    .addComponent(courseNameLabelShow))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseCreditsLabelEdit)
                    .addComponent(courseCreditsFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseMaxStudentsFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseMaxStudentsLabelEdit))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseLocationLabelEdit)
                    .addComponent(courseLocationFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneEditCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneEditCourseBtnActionPerformed
        // TODO add your handling code here:
        String courseCredits = courseCreditsFieldEdit.getText();
        String courseMaxStudent = courseMaxStudentsFieldEdit.getText();
        String courseLocation = courseLocationFieldEdit.getText();
        course.setCourseCredits(Integer.parseInt(courseCredits));
        course.setMaxStudentsRegister(Integer.parseInt(courseMaxStudent));
        course.setCourseLocation(courseLocation);
        Controller.courseEditController(course, this);
    }//GEN-LAST:event_doneEditCourseBtnActionPerformed

    private void backEditCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backEditCourseBtnActionPerformed
        this.dispose();
        new AdminManipulateCourseView().setVisible(true);
    }//GEN-LAST:event_backEditCourseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseEditInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseEditInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseEditInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseEditInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new CourseEditInformationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backEditCourseBtn;
    private javax.swing.JTextField courseCreditsFieldEdit;
    private javax.swing.JLabel courseCreditsLabelEdit;
    private javax.swing.JTextField courseLocationFieldEdit;
    private javax.swing.JLabel courseLocationLabelEdit;
    private javax.swing.JTextField courseMaxStudentsFieldEdit;
    private javax.swing.JLabel courseMaxStudentsLabelEdit;
    private javax.swing.JLabel courseNameLabelEdit;
    private javax.swing.JLabel courseNameLabelShow;
    private javax.swing.JButton doneEditCourseBtn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
