/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.StudentView;
    
import Controllers.Controller;
import static Controllers.TrainLBPH.trainLBPH;
import Models.User;
import Models.User_Model;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import org.bytedeco.javacpp.BytePointer;
import static org.bytedeco.opencv.global.opencv_imgcodecs.imencode;
import static org.bytedeco.opencv.global.opencv_imgcodecs.imwrite;
import org.bytedeco.opencv.global.opencv_imgproc;
import static org.bytedeco.opencv.global.opencv_imgproc.COLOR_BGRA2GRAY;
import static org.bytedeco.opencv.global.opencv_imgproc.cvtColor;
import org.bytedeco.opencv.opencv_core.Mat;
import org.bytedeco.opencv.opencv_core.Rect;
import org.bytedeco.opencv.opencv_core.RectVector;
import org.bytedeco.opencv.opencv_core.Scalar;
import org.bytedeco.opencv.opencv_core.Size;
import org.bytedeco.opencv.opencv_objdetect.CascadeClassifier;
import org.bytedeco.opencv.opencv_videoio.VideoCapture;

/**
 *
 * @author Quan's PC
 */
public class StudentEditInformationView extends javax.swing.JFrame {
    private User user;
    
    // JavaCV
    private final int numberFacesSave = 25;
    private int capture = 1;
    private DaemonThread myThread = null;
    private VideoCapture webSource = null;
    private Mat cameraImage = new Mat();
    private CascadeClassifier cascade = new CascadeClassifier("D:\\Programs\\OpenCv\\openCV\\sources\\data\\haarcascades\\haarcascade_frontalface_alt.xml");
    private BytePointer mem = new BytePointer();
    private RectVector detectedFaces = new RectVector();
    
    
    public StudentEditInformationView() {
        initComponents();
        setTitle("Student Edit Information");
        user = Controller.getUser();
        usernameFieldEdit.setText(user.getUsername());
        passwordFieldEdit.setText(user.getPassword());
        phoneFieldEdit.setText(user.getPhone());
        emailFieldEdit.setText(user.getEmail());
        captureBtn.setEnabled(false);
        if(user.isIsFaceRecognized())FaceRecogzieBtn.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel2 = new javax.swing.JPanel();
        usernameLabelEdit = new javax.swing.JLabel();
        passwordLabelEdit = new javax.swing.JLabel();
        phoneLabelEdit = new javax.swing.JLabel();
        emailLabelEdit = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        doneEditsStudentBtn = new javax.swing.JButton();
        backEditStudentBtn = new javax.swing.JButton();
        usernameFieldEdit = new javax.swing.JTextField();
        emailFieldEdit = new javax.swing.JTextField();
        passwordFieldEdit = new javax.swing.JTextField();
        phoneFieldEdit = new javax.swing.JTextField();
        cameraPanel = new javax.swing.JPanel();
        FaceRecogzieBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        captureBtn = new javax.swing.JButton();
        lablePicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT EDIT INFORMATION");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);
        jPanel1.add(filler1, java.awt.BorderLayout.PAGE_START);

        usernameLabelEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameLabelEdit.setText("Username:");

        passwordLabelEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwordLabelEdit.setText("Password:");

        phoneLabelEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phoneLabelEdit.setText("Phone:");

        emailLabelEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailLabelEdit.setText("Email:");

        doneEditsStudentBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        doneEditsStudentBtn.setText("Done");
        doneEditsStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneEditsStudentBtnActionPerformed(evt);
            }
        });

        backEditStudentBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backEditStudentBtn.setText("Back");
        backEditStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backEditStudentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(backEditStudentBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(doneEditsStudentBtn)
                .addGap(48, 48, 48))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneEditsStudentBtn)
                    .addComponent(backEditStudentBtn)))
        );

        usernameFieldEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        emailFieldEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        passwordFieldEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        phoneFieldEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabelEdit)
                    .addComponent(passwordLabelEdit)
                    .addComponent(phoneLabelEdit)
                    .addComponent(emailLabelEdit))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phoneFieldEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(passwordFieldEdit)
                    .addComponent(emailFieldEdit)
                    .addComponent(usernameFieldEdit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabelEdit)
                    .addComponent(usernameFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabelEdit)
                    .addComponent(passwordFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabelEdit))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabelEdit)
                    .addComponent(emailFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        cameraPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        FaceRecogzieBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FaceRecogzieBtn.setText("Add Face Recognize");
        FaceRecogzieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaceRecogzieBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cameraPanelLayout = new javax.swing.GroupLayout(cameraPanel);
        cameraPanel.setLayout(cameraPanelLayout);
        cameraPanelLayout.setHorizontalGroup(
            cameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cameraPanelLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(FaceRecogzieBtn)
                .addGap(138, 138, 138))
        );
        cameraPanelLayout.setVerticalGroup(
            cameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cameraPanelLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(FaceRecogzieBtn)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        captureBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        captureBtn.setText("Capture");

        lablePicture.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lablePicture.setText("0/25");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(captureBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lablePicture)
                .addGap(70, 70, 70))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(captureBtn)
                    .addComponent(lablePicture))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cameraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cameraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneEditsStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneEditsStudentBtnActionPerformed
        // TODO add your handling code here:
        String newUsername = usernameFieldEdit.getText();
        String newPassword = passwordFieldEdit.getText();
        String newPhone = phoneFieldEdit.getText();
        String newEmail = emailFieldEdit.getText();
        user.setUsername(newUsername.trim());
        user.setPassword(newPassword.trim());
        user.setPhone(newPhone.trim());
        user.setEmail(newEmail.trim());
        Controller.userEditController(user, this);
    }//GEN-LAST:event_doneEditsStudentBtnActionPerformed

    private void backEditStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backEditStudentBtnActionPerformed
        this.dispose();
        new StudentMenuView().setVisible(true);
    }//GEN-LAST:event_backEditStudentBtnActionPerformed

    private void FaceRecogzieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaceRecogzieBtnActionPerformed
        // TODO add your handling code here:
        FaceRecogzieBtn.setEnabled(false);
        FaceRecogzieBtn.setVisible(false);
        captureBtn.setEnabled(true);
        startCamera();
    }//GEN-LAST:event_FaceRecogzieBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentEditInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentEditInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentEditInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentEditInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new StudentEditInformationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FaceRecogzieBtn;
    private javax.swing.JButton backEditStudentBtn;
    private javax.swing.JPanel cameraPanel;
    private javax.swing.JButton captureBtn;
    private javax.swing.JButton doneEditsStudentBtn;
    private javax.swing.JTextField emailFieldEdit;
    private javax.swing.JLabel emailLabelEdit;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lablePicture;
    private javax.swing.JTextField passwordFieldEdit;
    private javax.swing.JLabel passwordLabelEdit;
    private javax.swing.JTextField phoneFieldEdit;
    private javax.swing.JLabel phoneLabelEdit;
    private javax.swing.JTextField usernameFieldEdit;
    private javax.swing.JLabel usernameLabelEdit;
    // End of variables declaration//GEN-END:variables
    
     class DaemonThread implements Runnable {

        protected volatile boolean runnable = false;

        @Override
        public void run() {
            synchronized (this) {
                while (runnable) {
                    try {
                        if (webSource.grab()) {
                            webSource.retrieve(cameraImage);
                            Graphics graphics = cameraPanel.getGraphics();

                            Mat imageColor = new Mat();
                            imageColor = cameraImage;

                            Mat imageGray = new Mat();
                            cvtColor(imageColor, imageGray, COLOR_BGRA2GRAY);

                            cascade.detectMultiScale(imageColor, detectedFaces, 1.1, 1, 1, new Size(150, 150), new Size(600, 600));

                            for (int i = 0; i < detectedFaces.size(); i++) {
                                Rect rectengleDraw = detectedFaces.get(i);
                                opencv_imgproc.rectangle(imageColor, rectengleDraw, new Scalar(0, 255, 0, 1), 3, 0, 0);

                                Mat face = new Mat(imageGray, rectengleDraw);
                                opencv_imgproc.resize(face, face, new Size(160, 160));

                                if (captureBtn.getModel().isPressed()) {
                                    if (capture <= numberFacesSave) {
                                        String cropped = "photos\\person." + user.getUserId() + "." + capture + ".jpg";
                                        imwrite(cropped, face);

                                        lablePicture.setText(String.valueOf(capture) + "/" + numberFacesSave);
                                        capture++;
                                    }

                                    if (capture >= numberFacesSave) {
                                        trainLBPH();
                                        setUserFaceRecognize();
                                        System.out.println("File Generated");
                                        stopCamera();
                                    }
                                }

                            }

                            imencode(".bmp", cameraImage, mem);
                            Image im = ImageIO.read(new ByteArrayInputStream(mem.getStringBytes()));
                            BufferedImage buff = (BufferedImage) im;

                            if (graphics.drawImage(buff, 0, 0, cameraPanel.getWidth(), cameraPanel.getHeight(), 0, 0, buff.getWidth(), buff.getHeight(), null)) {
                                if (runnable == false) {
                                    System.out.println("Stop camera");
                                    this.wait();
                                }
                            }
                        }
                    } catch (HeadlessException | IOException | InterruptedException e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(rootPane, e.getMessage());
                    }
                }
            }
        }
    }

    private void setUserFaceRecognize() {
        User_Model.updateUserFaceRecogzie(user.getUserId());
    }

    public void stopCamera() {
        myThread.runnable = false;
        webSource.release();
        JOptionPane.showMessageDialog(rootPane, "Successfully Add Face Recognize");
        captureBtn.setEnabled(false);
    }

    public void startCamera() {
        new Thread() {
            @Override
            public void run() {
                webSource = new VideoCapture(0);
                myThread = new DaemonThread();
                Thread t = new Thread(myThread);
                t.setDaemon(true);
                myThread.runnable = true;
                t.start();
            }
        }.start();
    }

}
