/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.AdminView;

import Controllers.Controller;
import Models.User;
import Models.User_Model;

/**
 *
 * @author Quan's PC
 */
public class AdminRegisterFacultyView extends javax.swing.JFrame {
    private User faculty;
    /**
     * Creates new form AdminMenuView
     */
    public AdminRegisterFacultyView() {
        initComponents();
        setTitle("Register Faculty");
        faculty = new User();
        faculty.setUserId( User_Model.getNewUserId());
        faculty.setUserRole("faculty");
        facultyIdFieldRegister.setText(faculty.getUserId()+"");
        facultyIdFieldRegister.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel2 = new javax.swing.JPanel();
        usernameLabelRegister = new javax.swing.JLabel();
        passwordLabelRegister = new javax.swing.JLabel();
        phoneLabelRegister = new javax.swing.JLabel();
        emailLabelRegister = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        doneFacultyAdminBtn = new javax.swing.JButton();
        backFacultyAdminBtn = new javax.swing.JButton();
        usernameFieldRegister = new javax.swing.JTextField();
        emailFieldRegister = new javax.swing.JTextField();
        passwordFieldRegister = new javax.swing.JTextField();
        phoneFieldRegister = new javax.swing.JTextField();
        facultyIdLabelRegister = new javax.swing.JLabel();
        facultyIdFieldRegister = new javax.swing.JTextField();
        firsetNameLabelRegister = new javax.swing.JLabel();
        firstNameFieldRegister = new javax.swing.JTextField();
        midNameLabelRegister = new javax.swing.JLabel();
        midNameFieldRegister = new javax.swing.JTextField();
        lastNameLabelRegister = new javax.swing.JLabel();
        lastNameFieldRegister = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN REGISTER FACULTY");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);
        jPanel1.add(filler1, java.awt.BorderLayout.PAGE_START);

        usernameLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameLabelRegister.setText("Username:");

        passwordLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabelRegister.setText("Password:");

        phoneLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneLabelRegister.setText("Phone:");

        emailLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailLabelRegister.setText("Email:");

        doneFacultyAdminBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        doneFacultyAdminBtn.setText("Done");
        doneFacultyAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneFacultyAdminBtnActionPerformed(evt);
            }
        });

        backFacultyAdminBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backFacultyAdminBtn.setText("Back");
        backFacultyAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backFacultyAdminBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(backFacultyAdminBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doneFacultyAdminBtn)
                .addGap(48, 48, 48))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneFacultyAdminBtn)
                    .addComponent(backFacultyAdminBtn)))
        );

        usernameFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        emailFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        passwordFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        phoneFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        facultyIdLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        facultyIdLabelRegister.setText("Faculty ID:");

        facultyIdFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        firsetNameLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firsetNameLabelRegister.setText("FirstName:");

        firstNameFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        midNameLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        midNameLabelRegister.setText("MidName:");

        midNameFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lastNameLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastNameLabelRegister.setText("LastName:");

        lastNameFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLabelRegister)
                            .addComponent(passwordLabelRegister)
                            .addComponent(phoneLabelRegister)
                            .addComponent(emailLabelRegister))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(passwordFieldRegister, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameFieldRegister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                            .addComponent(phoneFieldRegister)
                            .addComponent(emailFieldRegister)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firsetNameLabelRegister)
                            .addComponent(facultyIdLabelRegister))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(firstNameFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(midNameLabelRegister)
                                .addGap(18, 18, 18)
                                .addComponent(midNameFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lastNameLabelRegister)
                                .addGap(18, 18, 18)
                                .addComponent(lastNameFieldRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                            .addComponent(facultyIdFieldRegister))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultyIdLabelRegister)
                    .addComponent(facultyIdFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firsetNameLabelRegister)
                    .addComponent(firstNameFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midNameLabelRegister)
                    .addComponent(midNameFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabelRegister)
                    .addComponent(lastNameFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabelRegister)
                    .addComponent(usernameFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabelRegister)
                    .addComponent(passwordFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabelRegister))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabelRegister)
                    .addComponent(emailFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneFacultyAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneFacultyAdminBtnActionPerformed
        // TODO add your handling code here:
        String firstName = firstNameFieldRegister.getText();
        String midName = midNameFieldRegister.getText();
        String lastName = lastNameFieldRegister.getText();
        String userName = usernameFieldRegister.getText();
        String password = passwordFieldRegister.getText();
        String phone = phoneFieldRegister.getText();
        String emaail = emailFieldRegister.getText();
        faculty.setFirstName(firstName.trim());
        faculty.setMidName(midName.trim());
        faculty.setLastName(lastName.trim());
        faculty.setUsername(userName.trim());
        faculty.setPassword(password.trim());
        faculty.setPhone(phone.trim());
        faculty.setEmail(emaail.trim());
        Controller.userRegisterFacultyController(faculty, this);
    }//GEN-LAST:event_doneFacultyAdminBtnActionPerformed

    private void backFacultyAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backFacultyAdminBtnActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new AdminMenuView().setVisible(true);
    }//GEN-LAST:event_backFacultyAdminBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterFacultyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterFacultyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterFacultyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterFacultyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRegisterFacultyView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backFacultyAdminBtn;
    private javax.swing.JButton doneFacultyAdminBtn;
    private javax.swing.JTextField emailFieldRegister;
    private javax.swing.JLabel emailLabelRegister;
    private javax.swing.JTextField facultyIdFieldRegister;
    private javax.swing.JLabel facultyIdLabelRegister;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel firsetNameLabelRegister;
    private javax.swing.JTextField firstNameFieldRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField lastNameFieldRegister;
    private javax.swing.JLabel lastNameLabelRegister;
    private javax.swing.JTextField midNameFieldRegister;
    private javax.swing.JLabel midNameLabelRegister;
    private javax.swing.JTextField passwordFieldRegister;
    private javax.swing.JLabel passwordLabelRegister;
    private javax.swing.JTextField phoneFieldRegister;
    private javax.swing.JLabel phoneLabelRegister;
    private javax.swing.JTextField usernameFieldRegister;
    private javax.swing.JLabel usernameLabelRegister;
    // End of variables declaration//GEN-END:variables
}
